#!/usr/bin/env node
/**
 * Regenerates src/protocols/lz-risk/dvns.json from LayerZero's own metadata.
 *
 *   node scripts/gen-lz-dvns.mjs          write the file
 *   node scripts/gen-lz-dvns.mjs --check  fail if the committed file is not what the API says
 *
 * Source: https://metadata.layerzero-api.com/v1/metadata/dvns — the list LayerZero publishes of
 * every DVN it knows, per chain, with `deprecated` set on the ones that must not be relied on. The
 * dead DVN (`LZDeadDVN`, id `lz-dead-dvn`) is in there as a deprecated entry: a route configured
 * with it can never be verified by anyone, which is why §4 treats it as a hard block rather than a
 * warning.
 *
 * The result is COMMITTED and read from disk at runtime. A risk verdict that depended on a live
 * fetch would be a verdict a server could change, and §0 does not allow that.
 *
 * **Chains are matched by native chain id, never by name.** The two metadata endpoints disagree
 * about what some chains are called — Linea is `chainKey: "linea"` in the deployments feed but
 * `zkconsensys` in the DVN feed — so the deployments feed's own top-level key (stage suffix
 * stripped) is what indexes the DVN feed, and the link between them is the chain id. A project
 * chain that cannot be resolved fails the script instead of quietly getting an empty DVN list,
 * because an empty list would read as "no DVN here is deprecated".
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CHAINS } from '../src/core/chains.ts'

const DVN_SOURCE = 'https://metadata.layerzero-api.com/v1/metadata/dvns'
const DEPLOYMENTS_SOURCE = 'https://metadata.layerzero-api.com/v1/metadata/deployments'
const ROOT = new URL('..', import.meta.url).pathname
const OUT = join(ROOT, 'src/protocols/lz-risk/dvns.json')

const check = process.argv.includes('--check')

async function getJson(url) {
  const r = await fetch(url)
  if (!r.ok) {
    console.error(`${url} answered ${r.status}`)
    process.exit(1)
  }
  return r.json()
}

const [deployments, dvnFeed] = await Promise.all([getJson(DEPLOYMENTS_SOURCE), getJson(DVN_SOURCE)])

/**
 * native chain id -> the deployments feed's top-level key with the stage suffix stripped, which is
 * how the DVN feed names the same chain.
 */
const keyByChainId = new Map()
for (const [topKey, entry] of Object.entries(deployments)) {
  const cd = entry?.chainDetails
  if (!cd || cd.chainType !== 'evm' || cd.nativeChainId === undefined) continue
  if (!(entry.deployments ?? []).some((d) => d.stage === 'mainnet')) continue
  keyByChainId.set(cd.nativeChainId, topKey.replace(/-mainnet$/, ''))
}
// Solana has no EVM chain id; it is named the same in both feeds.
const SVM_KEYS = { solana: 'solana' }

const chains = {}
const unresolved = []
for (const c of CHAINS) {
  const metaKey = c.vm === 'evm' ? keyByChainId.get(c.chainId) : SVM_KEYS[c.key]
  const entry = metaKey ? dvnFeed[metaKey] : undefined
  if (!entry || entry.environment !== 'mainnet' || !entry.dvns) {
    unresolved.push({ key: c.key, metaKey: metaKey ?? '(none)' })
    continue
  }
  const dvns = {}
  for (const [address, d] of Object.entries(entry.dvns)) {
    // EVM addresses are lowercased so a lookup never depends on checksum casing; a Solana DVN is
    // base58 and case-significant, so it is kept verbatim.
    const key = /^0x[0-9a-fA-F]{40}$/.test(address) ? address.toLowerCase() : address
    dvns[key] = {
      name: d.canonicalName ?? d.id ?? 'unknown',
      id: d.id ?? '',
      version: d.version ?? 0,
      deprecated: d.deprecated === true,
    }
  }
  chains[c.key] = { metadataKey: metaKey, dvns }
}

if (unresolved.length) {
  for (const u of unresolved) console.error(`${u.key}: no mainnet DVN entry (looked for "${u.metaKey}")`)
  console.error('\nRefusing to write a table with a chain missing: an empty DVN list reads as "nothing here is deprecated".')
  process.exit(1)
}

const doc = {
  $source: DVN_SOURCE,
  $resolvedVia: `${DEPLOYMENTS_SOURCE} (native chain id -> metadata key; the two feeds name some chains differently)`,
  $generated: new Date().toISOString().slice(0, 10),
  $note: 'Generated by scripts/gen-lz-dvns.mjs. Never fetched at runtime. `deprecated` is LayerZero\'s own flag; LZDeadDVN (id lz-dead-dvn) carries it.',
  chains,
}
const text = `${JSON.stringify(doc, null, 2)}\n`

if (check) {
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {
    console.error(`${OUT} does not exist — run without --check`)
    process.exit(1)
  }
  const strip = (s) => JSON.stringify({ ...JSON.parse(s), $generated: '' })
  if (strip(current) !== strip(text)) {
    console.error('src/protocols/lz-risk/dvns.json is out of date with the metadata API')
    process.exit(1)
  }
  console.log(`dvns.json matches ${DVN_SOURCE}`)
} else {
  writeFileSync(OUT, text)
  const total = Object.values(chains).reduce((n, c) => n + Object.keys(c.dvns).length, 0)
  const dead = Object.values(chains).reduce((n, c) => n + Object.values(c.dvns).filter((d) => d.deprecated).length, 0)
  console.log(`wrote ${OUT} — ${Object.keys(chains).length} chains, ${total} DVNs, ${dead} deprecated`)
  for (const [key, c] of Object.entries(chains)) {
    const names = Object.values(c.dvns)
      .filter((d) => d.id === 'lz-dead-dvn')
      .map((d) => d.name)
    if (names.length) console.log(`  ${key}: dead DVN present in the list (${names.join(', ')})`)
  }
}
